# Generated by Django 4.2.1 on 2023-05-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_zipcode'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machine',
            new_name='Car',
        ),
    ]
